import type { Session } from "../src/types";

export function session(overrides: Partial<Session> = {}): Session {
  return {
    id: "2026-09-05T18:12:04_v001",
    vehicle_id: "v001",
    vehicle_name: "Car One",
    card_uid: null,
    card_label: null,
    location: "home",
    identification_source: "manual",
    identification_conflict: false,
    plug_start: "2026-09-05T18:12:04+02:00",
    plug_end: "2026-09-05T20:12:04+02:00",
    plug_duration_min: 120,
    charge_duration_min: 120,
    pause_duration_min: 0,
    phases_recorded: false,
    soc_start: 20,
    soc_end: 80,
    odometer_km: 1000,
    energy_kwh: 10,
    energy_is_estimate: false,
    energy_grid_kwh: null,
    energy_solar_kwh: null,
    energy_unallocated_kwh: 0,
    cost: 3,
    charge_type: "ac",
    power_avg_kw: 5,
    address: null,
    latitude: null,
    longitude: null,
    location_conflict: false,
    provider: null,
    note: null,
    charge_error: false,
    status: "complete",
    open_fields: [],
    phases: [],
    ...overrides,
  };
}
